crudpro/urls.py
from django.contrib import admin
from django.urls import path
from  crudpro_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',views.List.as_view(),name='home'),
    path('create/',views.Create.as_view(),name='create'),
    path('update/',views.Update.as_view,name='update'),
]

crudpro_app/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class Student(models.Model):
    name=models.CharField(max_length=25)
    age=models.PositiveIntegerField()
    address=models.TextField()
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('home')

crudpro_app/views.py
from django.shortcuts import render
from django.views.generic import ListView,CreateView,UpdateView,DetailView,DeleteView
from crudpro_app.models import Student
# Create your views here.
class List(ListView):
    model = Student
    template_name = 'list.html'
class Create(CreateView):
    model = Student
    template_name = 'create.html'
    fields = ('__all__')
class Update(UpdateView):
    model = Student
    template_name = 'update.html'
    fields = ('__all__')

templates/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Create new member details</h1>
<form method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value="Create">
</form>
</body>
</html>

templates/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>This is detail page</h1>
</body>
</html>

templates/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Welcome to list page...</title>

</head>
<body>
<h1>This is the List of Members</h1>
<table border= 1px>

    <tr>
       <th>ID</th>
       <th>Name</th>
       <th>Age</th>
       <th>Address</th>
    </tr>

    <tr>
        {% for x in student_list %}
        <td>{{ x.id }}</td>
       <td>{{ x.name }}</td>
        <td>{{ x.age }}</td>
        <td>{{ x.address }}</td>
    </tr>

{% endfor %}
</table>
<a href="create">Add Member</a>
</body>
</html>

templates/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Welcome to update page</title>
</head>
<body>
<h1>This is update page</h1>
</body>
</html>